In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [30]:
bvc = np.array([1, 1, 1, 0])
pc = np.array([1, 0])

In [31]:
bvc2pc = np.outer(bvc, pc)
pc2bvc = bvc2pc.T

In [32]:
bvc2pc

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 0]])

In [38]:
(bvc2pc/np.maximum(bvc2pc.sum(1, keepdims=True), 1e-7))@pc

array([1., 1., 1., 0.])

In [39]:
(pc2bvc/np.maximum(pc2bvc.sum(1, keepdims=True), 1e-7))@bvc

array([1., 0.])

In [142]:
n_modules = 2
n_pc = 2
n_bvc = 4
initial_g = np.ones((2, 2))/2
initial_g

array([[0.5, 0.5],
       [0.5, 0.5]])

In [143]:
initial_bvc2g = np.ones((n_bvc, n_modules, n_pc))/3

In [144]:
# initial_bvc2g /= np.maximum(initial_bvc2g.sum(2, keepdims=True), 1e-7)

In [145]:
bvc2g_act_all = np.zeros((n_modules, n_pc))

for col in range(n_pc):
    bvc2g_act = initial_bvc2g[:, :, col].T@bvc
    bvc2g_act_all[:, col] = bvc2g_act


bvc2g_act_all # n_modules x n_pc

array([[1., 1.],
       [1., 1.]])

In [157]:
bvc2g_res_act = np.zeros_like(bvc2g_act_all)

bvc2g_res_act[0, :] = bvc2g_act_all[0, :]

for col in range(n_pc):
    bvc2g_res_act[-1, col] = bvc2g_act_all[-1, col] - .5*bvc2g_act_all[-1, (col+1)%n_pc]

In [158]:
bvc2g_res_act

array([[1. , 1. ],
       [0.5, 0.5]])