In [1]:
import os
import sys
sys.path.insert(1, os.path.realpath(os.path.pardir))
import numpy as np

In [2]:
from bbtoolkit.structures.synapses import NeuralMass, NeuralWeights


weights_1 = NeuralMass(
    NeuralWeights(
        from_='a',
        to='b',
        weights=np.array([[1, 2, 3, 4]]),
    ),
    NeuralWeights(
        from_='b',
        to='c',
        weights=np.array([[9, 10, 11, 12]]),
    )
)
weights_2 = NeuralMass(
    NeuralWeights(
        from_='b',
        to='a',
        weights=np.array([[1, 2, 3, 4]]),
    ),
    NeuralWeights(
        from_='a',
        to='b',
        weights=np.array([[5, 6, 7, 8]]),
    )
)

In [3]:
weights_2t = weights_2.T

In [4]:
weights_2t.a.to.b

array([[5],
       [6],
       [7],
       [8]])

In [5]:
weights_3 = weights_1 - weights_2

In [6]:
weights_3.a.to.b

array([[-4, -4, -4, -4]])

In [7]:
weights_4 = -weights_3

In [8]:
weights_4.a.to.b

array([[4, 4, 4, 4]])

In [9]:
weights_4.connection_map

a  b  c
a  0  1  0
b  0  0  1

In [10]:
abs(weights_3).a.to.b

array([[4, 4, 4, 4]])

In [11]:
weights_2.a.to.b

array([[5, 6, 7, 8]])

In [12]:
weights_1.a.to.b@(weights_2.a.to.b).T

array([[70]])

In [13]:
weights_5 = weights_1 @ weights_2.T

In [14]:
weights_5.a.to.b

array([[70]])

In [15]:
weights_6 = weights_2 @ weights_1.T

In [16]:
weights_6.a.to.b

array([[70]])

In [17]:
weights_6.a.to.b -= 10
weights_6.a.to.b

array([[60]])

In [19]:
weights_6['a', 'b']

array([[60]])