# Disclamer: Example here is NOT a neural model

This is a simple example showing how to use TensorGroup and DirectedTensorGroup classes.


In [1]:
import os
import sys
sys.path.insert(1, os.path.realpath(os.path.pardir))

import numpy as np

from bbtoolkit.structures.tensorgroups import TensorGroup, DirectedTensorGroup, NamedTensor, DirectedTensor

### Create TensorGroup

In [2]:
n_neurons = 10
n_synapses = 1000
n_timepoints = 10

w1 = np.random.rand(n_neurons, n_timepoints, n_synapses)
w2 = np.random.rand(n_synapses, n_timepoints)
w3 = np.random.rand(n_neurons, n_timepoints)


neural_data = TensorGroup(
    NamedTensor(
        'potentials',
        w1.copy()
    ),
    NamedTensor(
        'plasticity',
        w2.copy()
    ),
    NamedTensor(
        'rates',
        w3.copy()
    )
)

### How does it look like?

In [3]:
neural_data

TensorGroup(potentials: ((10, 10, 1000)), plasticity: ((1000, 10)), rates: ((10, 10)))

### Let's take a look what is inside rates

In [4]:
neural_data.rates

array([[0.4375681 , 0.26586352, 0.14220791, 0.38205243, 0.59603709,
        0.44504534, 0.00254881, 0.57584246, 0.70370608, 0.57245133],
       [0.22932506, 0.13221058, 0.95517244, 0.21074444, 0.02237982,
        0.76120744, 0.26532478, 0.62864019, 0.2424173 , 0.91929489],
       [0.54530063, 0.61215541, 0.36203934, 0.32925348, 0.19392067,
        0.57679211, 0.20497217, 0.22867237, 0.99387789, 0.49850833],
       [0.85493129, 0.56159765, 0.07814701, 0.21008373, 0.87283796,
        0.35564461, 0.95743348, 0.8005833 , 0.75096908, 0.48748988],
       [0.48337011, 0.02113998, 0.9896186 , 0.27132514, 0.02286618,
        0.88394514, 0.52313955, 0.44545802, 0.10654749, 0.31978303],
       [0.81827047, 0.55898988, 0.02712178, 0.35360691, 0.83580882,
        0.88875689, 0.79812387, 0.67486703, 0.37332261, 0.65359003],
       [0.76121944, 0.24619093, 0.18404694, 0.52869595, 0.24147184,
        0.717787  , 0.12166215, 0.16867429, 0.6688752 , 0.32437465],
       [0.49547568, 0.13838178, 0.1630701

### And how to access plasticity

In [5]:
neural_data.plasticity.min(), neural_data.plasticity.max()

(5.441784056814392e-06, 0.9999580583346502)

### Let's say, we need it to be distributed around 0

In [6]:
neural_data -= 0.5

### What do we see now?

In [7]:
neural_data.rates

array([[-0.0624319 , -0.23413648, -0.35779209, -0.11794757,  0.09603709,
        -0.05495466, -0.49745119,  0.07584246,  0.20370608,  0.07245133],
       [-0.27067494, -0.36778942,  0.45517244, -0.28925556, -0.47762018,
         0.26120744, -0.23467522,  0.12864019, -0.2575827 ,  0.41929489],
       [ 0.04530063,  0.11215541, -0.13796066, -0.17074652, -0.30607933,
         0.07679211, -0.29502783, -0.27132763,  0.49387789, -0.00149167],
       [ 0.35493129,  0.06159765, -0.42185299, -0.28991627,  0.37283796,
        -0.14435539,  0.45743348,  0.3005833 ,  0.25096908, -0.01251012],
       [-0.01662989, -0.47886002,  0.4896186 , -0.22867486, -0.47713382,
         0.38394514,  0.02313955, -0.05454198, -0.39345251, -0.18021697],
       [ 0.31827047,  0.05898988, -0.47287822, -0.14639309,  0.33580882,
         0.38875689,  0.29812387,  0.17486703, -0.12667739,  0.15359003],
       [ 0.26121944, -0.25380907, -0.31595306,  0.02869595, -0.25852816,
         0.217787  , -0.37833785, -0.33132571

In [8]:
neural_data.plasticity.min(), neural_data.plasticity.max()

(-0.4999945582159432, 0.49995805833465023)

### But can we change variables within the group?

In [9]:
some_crazy_rule = np.exp(1 - (neural_data.potentials@neural_data.plasticity).mean(-1))
neural_data.rates /= some_crazy_rule

### Works!

In [10]:
neural_data.rates

array([[-0.01723146, -0.11413112, -0.12494898, -0.08448989,  0.03014359,
        -0.01455516, -0.22911851,  0.01247747,  0.03964687,  0.05084605],
       [-0.23608711, -0.04634081,  0.04058095, -0.17119248, -0.34333101,
         0.05640139, -0.04559339,  0.02962628, -0.0180382 ,  0.16825328],
       [ 0.02296517,  0.02659846, -0.02795959, -0.01434298, -0.1002668 ,
         0.00949969, -0.25022725, -0.01753683,  0.14051646, -0.00096907],
       [ 0.40341979,  0.01489934, -0.55894851, -0.14853048,  0.16786591,
        -0.23334495,  0.09347986,  0.29473016,  0.05742345, -0.01624364],
       [-0.00468364, -0.17174078,  0.20591357, -0.0331035 , -0.27351499,
         0.02663909,  0.00927578, -0.00495752, -0.15613794, -0.09725065],
       [ 0.12327673,  0.00670079, -0.25664991, -0.10155475,  0.05343189,
         0.06739292,  0.08414997,  0.01403295, -0.03674664,  0.03717096],
       [ 0.16386089, -0.16983087, -0.21871366,  0.01293949, -0.06490282,
         0.09350111, -0.09133371, -0.10825115

### What if I need some operation to be done on the group? For example x*sin(x)

In [11]:
neural_data.map(lambda x: x*np.sin(x), inplace=True)

TensorGroup(potentials: ((10, 10, 1000)), plasticity: ((1000, 10)), rates: ((10, 10)))

In [12]:
neural_data.rates

array([[2.96908402e-04, 1.29976520e-02, 1.55716547e-02, 7.13005187e-03,
        9.08498424e-04, 2.11845291e-04, 5.20372020e-02, 1.55683225e-04,
        1.57146285e-03, 2.58420651e-03],
       [5.52207957e-02, 2.14670258e-03, 1.64636130e-03, 2.91639256e-02,
        1.15573993e-01, 3.17943037e-03, 2.07803750e-03, 8.77588023e-04,
        3.25359172e-04, 2.81757873e-02],
       [5.27352713e-04, 7.07394527e-04, 7.81636751e-04, 2.05714157e-04,
        1.00365941e-02, 9.02427152e-05, 6.19623061e-02, 3.07524785e-04,
        1.96799618e-02, 9.39095217e-07],
       [1.58368852e-01, 2.21982189e-04, 2.96407609e-01, 2.19802750e-02,
        2.80468075e-02, 5.39570768e-02, 8.72576294e-03, 8.56137039e-02,
        3.29564125e-03, 2.63844242e-04],
       [2.19364150e-05, 2.93501166e-02, 4.21014013e-02, 1.09564183e-03,
        7.38811677e-02, 7.09557109e-04, 8.60387878e-05, 2.45768788e-05,
        2.42801212e-02, 9.44278758e-03],
       [1.51586882e-02, 4.49002134e-05, 6.51484295e-02, 1.02956494e-02,
   

### Can we do opeations between two groups?

In [13]:
neural_data_1 = TensorGroup(
    NamedTensor(
        'potentials',
        np.array([1, 1, 1, 1])
    ),
    NamedTensor(
        'plasticity',
        np.array([2, 2, 2, 2, 2])
    ),
    NamedTensor(
        'rates',
        np.array([1, 2, 3, 4])
    )
)

neural_data_2 = TensorGroup(
    NamedTensor(
        'potentials',
        np.array([.5, .5, .5, .5])
    ),
    NamedTensor(
        'plasticity',
        np.array([4, 4, 4, 4, 4])
    ),
    NamedTensor(
        'rates',
        np.array([4, 3, 2, 1])
    )
)

neural_data = neural_data_1 * neural_data_2

In [14]:
neural_data.potentials

array([0.5, 0.5, 0.5, 0.5])

In [15]:
neural_data.plasticity

array([8, 8, 8, 8, 8])

In [16]:
neural_data.rates

array([4, 6, 6, 4])

### What if mathematical operations is not enough and I need 1st multiplied by sin of 2nd?

In [17]:
neural_data = neural_data_1.operation_with(neural_data_2, lambda x, y: x * np.sin(y))

In [18]:
neural_data.potentials

array([0.47942554, 0.47942554, 0.47942554, 0.47942554])

In [19]:
neural_data.plasticity

array([-1.51360499, -1.51360499, -1.51360499, -1.51360499, -1.51360499])

In [20]:
neural_data.rates

array([-0.7568025 ,  0.28224002,  2.72789228,  3.36588394])

### How to combine 2 groups together?

In [21]:
neural_data_1 = TensorGroup(
    NamedTensor(
        'potentials',
        np.array([1, 1, 1, 1])
    ),
    NamedTensor(
        'plasticity',
        np.array([2, 2, 2, 2, 2])
    ),
    NamedTensor(
        'rates',
        np.array([1, 2, 3, 4])
    )
)

neural_data_2 = TensorGroup(
    NamedTensor(
        'spikes',
        np.array([1, 0, 0, 1])
    ),
    NamedTensor(
        'excitation',
        np.array([.1, .2, .3, .4, .5])
    ),
    NamedTensor(
        'inhibition',
        -np.array([.1, .2, .3, .4, .5])
    )
)

neural_data = neural_data_1 + neural_data_2

In [22]:
neural_data

TensorGroup(potentials: ((4,)), plasticity: ((5,)), rates: ((4,)), spikes: ((4,)), excitation: ((5,)), inhibition: ((5,)))

### What if I still like dictionaries more?

In [44]:
n_neurons = 10
n_synapses = 1000
n_timepoints = 100

neural_data = TensorGroup(
    potentials=w1.copy(),
    plasticity=w2.copy(),
    rates=w3.copy()
)

# or
# neural_data = TensorGroup(
#     {
#         'potentials': np.random.rand(n_neurons, n_timepoints, n_synapses),
#         'plasticity': np.random.rand(n_synapses, n_timepoints),
#         'rate': np.random.rand(n_neurons, n_timepoints)
#     }
# )

In [45]:
neural_data['rates']

array([[0.4375681 , 0.26586352, 0.14220791, 0.38205243, 0.59603709,
        0.44504534, 0.00254881, 0.57584246, 0.70370608, 0.57245133],
       [0.22932506, 0.13221058, 0.95517244, 0.21074444, 0.02237982,
        0.76120744, 0.26532478, 0.62864019, 0.2424173 , 0.91929489],
       [0.54530063, 0.61215541, 0.36203934, 0.32925348, 0.19392067,
        0.57679211, 0.20497217, 0.22867237, 0.99387789, 0.49850833],
       [0.85493129, 0.56159765, 0.07814701, 0.21008373, 0.87283796,
        0.35564461, 0.95743348, 0.8005833 , 0.75096908, 0.48748988],
       [0.48337011, 0.02113998, 0.9896186 , 0.27132514, 0.02286618,
        0.88394514, 0.52313955, 0.44545802, 0.10654749, 0.31978303],
       [0.81827047, 0.55898988, 0.02712178, 0.35360691, 0.83580882,
        0.88875689, 0.79812387, 0.67486703, 0.37332261, 0.65359003],
       [0.76121944, 0.24619093, 0.18404694, 0.52869595, 0.24147184,
        0.717787  , 0.12166215, 0.16867429, 0.6688752 , 0.32437465],
       [0.49547568, 0.13838178, 0.1630701

In [46]:
neural_data['plasticity'].min(), neural_data['plasticity'].max()

(5.441784056814392e-06, 0.9999580583346502)

In [47]:
for key in neural_data.keys():
    neural_data[key] -= .5

In [48]:
neural_data['rates']

array([[-0.0624319 , -0.23413648, -0.35779209, -0.11794757,  0.09603709,
        -0.05495466, -0.49745119,  0.07584246,  0.20370608,  0.07245133],
       [-0.27067494, -0.36778942,  0.45517244, -0.28925556, -0.47762018,
         0.26120744, -0.23467522,  0.12864019, -0.2575827 ,  0.41929489],
       [ 0.04530063,  0.11215541, -0.13796066, -0.17074652, -0.30607933,
         0.07679211, -0.29502783, -0.27132763,  0.49387789, -0.00149167],
       [ 0.35493129,  0.06159765, -0.42185299, -0.28991627,  0.37283796,
        -0.14435539,  0.45743348,  0.3005833 ,  0.25096908, -0.01251012],
       [-0.01662989, -0.47886002,  0.4896186 , -0.22867486, -0.47713382,
         0.38394514,  0.02313955, -0.05454198, -0.39345251, -0.18021697],
       [ 0.31827047,  0.05898988, -0.47287822, -0.14639309,  0.33580882,
         0.38875689,  0.29812387,  0.17486703, -0.12667739,  0.15359003],
       [ 0.26121944, -0.25380907, -0.31595306,  0.02869595, -0.25852816,
         0.217787  , -0.37833785, -0.33132571

In [49]:
neural_data['plasticity'].min(), neural_data['plasticity'].max()

(-0.4999945582159432, 0.49995805833465023)

In [50]:
some_crazy_rule = np.exp(1 - (neural_data['potentials']@neural_data['plasticity']).mean(-1))
neural_data['rates'] /= some_crazy_rule

In [51]:
neural_data['rates']

array([[-0.01723146, -0.11413112, -0.12494898, -0.08448989,  0.03014359,
        -0.01455516, -0.22911851,  0.01247747,  0.03964687,  0.05084605],
       [-0.23608711, -0.04634081,  0.04058095, -0.17119248, -0.34333101,
         0.05640139, -0.04559339,  0.02962628, -0.0180382 ,  0.16825328],
       [ 0.02296517,  0.02659846, -0.02795959, -0.01434298, -0.1002668 ,
         0.00949969, -0.25022725, -0.01753683,  0.14051646, -0.00096907],
       [ 0.40341979,  0.01489934, -0.55894851, -0.14853048,  0.16786591,
        -0.23334495,  0.09347986,  0.29473016,  0.05742345, -0.01624364],
       [-0.00468364, -0.17174078,  0.20591357, -0.0331035 , -0.27351499,
         0.02663909,  0.00927578, -0.00495752, -0.15613794, -0.09725065],
       [ 0.12327673,  0.00670079, -0.25664991, -0.10155475,  0.05343189,
         0.06739292,  0.08414997,  0.01403295, -0.03674664,  0.03717096],
       [ 0.16386089, -0.16983087, -0.21871366,  0.01293949, -0.06490282,
         0.09350111, -0.09133371, -0.10825115

In [52]:
for key, value in neural_data.items():
    neural_data[key] = value * np.sin(value)

In [53]:
neural_data['rates']

array([[2.96908402e-04, 1.29976520e-02, 1.55716547e-02, 7.13005187e-03,
        9.08498424e-04, 2.11845291e-04, 5.20372020e-02, 1.55683225e-04,
        1.57146285e-03, 2.58420651e-03],
       [5.52207957e-02, 2.14670258e-03, 1.64636130e-03, 2.91639256e-02,
        1.15573993e-01, 3.17943037e-03, 2.07803750e-03, 8.77588023e-04,
        3.25359172e-04, 2.81757873e-02],
       [5.27352713e-04, 7.07394527e-04, 7.81636751e-04, 2.05714157e-04,
        1.00365941e-02, 9.02427152e-05, 6.19623061e-02, 3.07524785e-04,
        1.96799618e-02, 9.39095217e-07],
       [1.58368852e-01, 2.21982189e-04, 2.96407609e-01, 2.19802750e-02,
        2.80468075e-02, 5.39570768e-02, 8.72576294e-03, 8.56137039e-02,
        3.29564125e-03, 2.63844242e-04],
       [2.19364150e-05, 2.93501166e-02, 4.21014013e-02, 1.09564183e-03,
        7.38811677e-02, 7.09557109e-04, 8.60387878e-05, 2.45768788e-05,
        2.42801212e-02, 9.44278758e-03],
       [1.51586882e-02, 4.49002134e-05, 6.51484295e-02, 1.02956494e-02,
   

In [54]:
neural_data_1 = TensorGroup({
    'potentials': np.array([1, 1, 1, 1]),
    'plasticity': np.array([2, 2, 2, 2, 2]),
    'rates': np.array([1, 2, 3, 4])
})

neural_data_2 = TensorGroup({
    'potentials': np.array([.5, .5, .5, .5]),
    'plasticity': np.array([4, 4, 4, 4, 4]),
    'rates': np.array([4, 3, 2, 1])
})

neural_data = TensorGroup()
for key in neural_data_1.keys():
    neural_data[key] = neural_data_1[key] * neural_data_2[key]

In [34]:
neural_data['potentials']

array([0.5, 0.5, 0.5, 0.5])

In [35]:
neural_data['plasticity']

array([8, 8, 8, 8, 8])

In [36]:
neural_data['rates']

array([4, 6, 6, 4])

In [37]:
neural_data = TensorGroup()
for key in neural_data_1.keys():
    neural_data[key] = neural_data_1[key] * np.sin(neural_data_2[key])

In [38]:
neural_data['potentials']

array([0.47942554, 0.47942554, 0.47942554, 0.47942554])

In [39]:
neural_data['plasticity']

array([-1.51360499, -1.51360499, -1.51360499, -1.51360499, -1.51360499])

In [40]:
neural_data['rates']

array([-0.7568025 ,  0.28224002,  2.72789228,  3.36588394])

In [55]:
neural_data_1 = TensorGroup(
    {
        'potentials': np.array([1, 1, 1, 1]),
        'plasticity': np.array([2, 2, 2, 2, 2]),
        'rates': np.array([1, 2, 3, 4])
    }
)



neural_data = neural_data_1.copy()
neural_data.update(
    {
        'spikes': np.array([1, 0, 0, 1]),
        'excitation': np.array([.1, .2, .3, .4, .5]),
        'inhibition': -np.array([.1, .2, .3, .4, .5])
    }
)

In [56]:
neural_data

TensorGroup(potentials: ((4,)), plasticity: ((5,)), rates: ((4,)), spikes: ((4,)), excitation: ((5,)), inhibition: ((5,)))

### Everything works! Let's save that

In [41]:
neural_data.save('./neural_data.pkl')

### And read

In [42]:
loaded_neural_data = TensorGroup.load('./neural_data.pkl')

In [43]:
np.all(loaded_neural_data.rates == neural_data.rates)

True