# Disclamer: Example here is NOT a neural model

This is a simple example showing how to use TensorGroup and DirectedTensorGroup classes.


In [1]:
import os
import sys
sys.path.insert(1, os.path.realpath(os.path.pardir))

import numpy as np

from bbtoolkit.structures.tensorgroups import TensorGroup, DirectedTensorGroup, NamedTensor, DirectedTensor

### Create TensorGroup

In [2]:
n_neurons = 10
n_synapses = 1000
n_timepoints = 10

w1 = np.random.rand(n_neurons, n_timepoints, n_synapses)
w2 = np.random.rand(n_synapses, n_timepoints)
w3 = np.random.rand(n_neurons, n_timepoints)


neural_data = TensorGroup(
    NamedTensor(
        'potentials',
        w1.copy()
    ),
    NamedTensor(
        'plasticity',
        w2.copy()
    ),
    NamedTensor(
        'rates',
        w3.copy()
    )
)

### How does it look like?

In [3]:
neural_data

TensorGroup(potentials: ((10, 10, 1000)), plasticity: ((1000, 10)), rates: ((10, 10)))

### Let's take a look what is inside rates

In [4]:
neural_data.rates

array([[0.52204761, 0.59265797, 0.25856925, 0.10785986, 0.81598852,
        0.93264882, 0.08565943, 0.41425655, 0.24621629, 0.42701444],
       [0.4468596 , 0.28251438, 0.32397303, 0.04865305, 0.56509122,
        0.11219784, 0.309262  , 0.25489199, 0.93840309, 0.79914837],
       [0.18119309, 0.22761645, 0.23941499, 0.29013364, 0.89963499,
        0.41632122, 0.78243297, 0.46283606, 0.44035838, 0.69753209],
       [0.63393529, 0.78405118, 0.3036635 , 0.08720888, 0.38903702,
        0.07006973, 0.55248663, 0.98170927, 0.22474091, 0.14495742],
       [0.03233896, 0.64247456, 0.17254489, 0.66644069, 0.04048339,
        0.65472692, 0.5432218 , 0.1863485 , 0.52492256, 0.06557487],
       [0.40485961, 0.15840864, 0.53858381, 0.32352748, 0.57657207,
        0.99257511, 0.11150721, 0.4729103 , 0.92390306, 0.98080936],
       [0.42862044, 0.05205699, 0.62063884, 0.88613878, 0.88430045,
        0.77347983, 0.25389497, 0.65390141, 0.94898988, 0.68696434],
       [0.1076473 , 0.03857778, 0.9932831

### And how to access plasticity

In [5]:
neural_data.plasticity.min(), neural_data.plasticity.max()

(0.00026848656952860317, 0.9999198841213022)

### Let's say, we need it to be distributed around 0

In [6]:
neural_data -= 0.5

### What do we see now?

In [7]:
neural_data.rates

array([[ 0.02204761,  0.09265797, -0.24143075, -0.39214014,  0.31598852,
         0.43264882, -0.41434057, -0.08574345, -0.25378371, -0.07298556],
       [-0.0531404 , -0.21748562, -0.17602697, -0.45134695,  0.06509122,
        -0.38780216, -0.190738  , -0.24510801,  0.43840309,  0.29914837],
       [-0.31880691, -0.27238355, -0.26058501, -0.20986636,  0.39963499,
        -0.08367878,  0.28243297, -0.03716394, -0.05964162,  0.19753209],
       [ 0.13393529,  0.28405118, -0.1963365 , -0.41279112, -0.11096298,
        -0.42993027,  0.05248663,  0.48170927, -0.27525909, -0.35504258],
       [-0.46766104,  0.14247456, -0.32745511,  0.16644069, -0.45951661,
         0.15472692,  0.0432218 , -0.3136515 ,  0.02492256, -0.43442513],
       [-0.09514039, -0.34159136,  0.03858381, -0.17647252,  0.07657207,
         0.49257511, -0.38849279, -0.0270897 ,  0.42390306,  0.48080936],
       [-0.07137956, -0.44794301,  0.12063884,  0.38613878,  0.38430045,
         0.27347983, -0.24610503,  0.15390141

In [8]:
neural_data.plasticity.min(), neural_data.plasticity.max()

(-0.4997315134304714, 0.49991988412130217)

### But can we change variables within the group?

In [9]:
some_crazy_rule = np.exp(1 - (neural_data.potentials@neural_data.plasticity).mean(-1))
neural_data.rates /= some_crazy_rule

### Works!

In [10]:
neural_data.rates

array([[ 0.0106168 ,  0.06617958, -0.30390672, -0.09439851,  0.06118212,
         0.10759845, -0.09603363, -0.08278522, -0.02880955, -0.02006303],
       [-0.04493903, -0.35599249, -0.14194274, -0.37300998,  0.01459291,
        -0.1933345 , -0.06831331, -0.13034074,  0.08491789,  0.05999704],
       [-0.13612079, -0.20196336, -0.27277751, -0.0044045 ,  0.20522596,
        -0.03140591,  0.09037196, -0.02863803, -0.00353677,  0.04598782],
       [ 0.09168234,  0.12816669, -0.12401489, -0.07713693, -0.05962388,
        -0.29530078,  0.00716716,  0.43666583, -0.0791373 , -0.10352288],
       [-0.09247643,  0.06643601, -0.4399926 ,  0.09056814, -0.09070296,
         0.01837217,  0.09035721, -0.09630976,  0.00666881, -0.14431626],
       [-0.04127368, -0.28626816,  0.01733473, -0.04519581,  0.12363269,
         0.15254722, -0.22173933, -0.00572849,  0.19396416,  0.25268557],
       [-0.00825059, -1.01852414,  0.04832768,  0.09244156,  0.0649442 ,
         0.08902416, -1.29824564,  0.13521787

### What if I need some operation to be done on the group? For example x*sin(x)

In [11]:
neural_data.map(lambda x: x*np.sin(x), inplace=True)

TensorGroup(potentials: ((10, 10, 1000)), plasticity: ((1000, 10)), rates: ((10, 10)))

In [12]:
neural_data.rates

array([[1.12714316e-04, 4.37654004e-03, 9.09441374e-02, 8.89784915e-03,
        3.74091723e-03, 1.15550994e-02, 9.20828945e-03, 6.84556781e-03,
        8.29875516e-04, 4.02498305e-04],
       [2.01883657e-03, 1.24070784e-01, 2.00801541e-02, 1.35932322e-01,
        2.12945551e-04, 3.71458097e-02, 4.66307956e-03, 1.69406462e-02,
        7.20238467e-03, 3.59748518e-03],
       [1.84717033e-02, 4.05124705e-02, 7.34882481e-02, 1.93995629e-05,
        4.18226685e-02, 9.86169315e-04, 8.15597871e-03, 8.20024780e-04,
        1.25087460e-05, 2.11413412e-03],
       [8.39388053e-03, 1.63817656e-02, 1.53403009e-02, 5.94420736e-03,
        3.55290110e-03, 8.59406859e-02, 5.13676971e-05, 1.84674931e-01,
        6.25617771e-03, 1.06978555e-02],
       [8.53970698e-03, 4.41049775e-03, 1.87407267e-01, 8.19137951e-03,
        8.21575014e-03, 3.37517629e-04, 8.15331976e-03, 9.26123806e-03,
        4.44727185e-05, 2.07549633e-02],
       [1.70303315e-03, 8.08347510e-02, 3.00477686e-04, 2.04196601e-03,
   

### Can we do opeations between two groups?

In [13]:
neural_data_1 = TensorGroup(
    NamedTensor(
        'potentials',
        np.array([1, 1, 1, 1])
    ),
    NamedTensor(
        'plasticity',
        np.array([2, 2, 2, 2, 2])
    ),
    NamedTensor(
        'rates',
        np.array([1, 2, 3, 4])
    )
)

neural_data_2 = TensorGroup(
    NamedTensor(
        'potentials',
        np.array([.5, .5, .5, .5])
    ),
    NamedTensor(
        'plasticity',
        np.array([4, 4, 4, 4, 4])
    ),
    NamedTensor(
        'rates',
        np.array([4, 3, 2, 1])
    )
)

neural_data = neural_data_1 * neural_data_2

In [14]:
neural_data.potentials

array([0.5, 0.5, 0.5, 0.5])

In [15]:
neural_data.plasticity

array([8, 8, 8, 8, 8])

In [16]:
neural_data.rates

array([4, 6, 6, 4])

### What if mathematical operations is not enough and I need 1st multiplied by sin of 2nd?

In [17]:
neural_data = neural_data_1.operation_with(neural_data_2, lambda x, y: x * np.sin(y))

In [18]:
neural_data.potentials

array([0.47942554, 0.47942554, 0.47942554, 0.47942554])

In [19]:
neural_data.plasticity

array([-1.51360499, -1.51360499, -1.51360499, -1.51360499, -1.51360499])

In [20]:
neural_data.rates

array([-0.7568025 ,  0.28224002,  2.72789228,  3.36588394])

### How to combine 2 groups together?

In [21]:
neural_data_1 = TensorGroup(
    NamedTensor(
        'potentials',
        np.array([1, 1, 1, 1])
    ),
    NamedTensor(
        'plasticity',
        np.array([2, 2, 2, 2, 2])
    ),
    NamedTensor(
        'rates',
        np.array([1, 2, 3, 4])
    )
)

neural_data_2 = TensorGroup(
    NamedTensor(
        'spikes',
        np.array([1, 0, 0, 1])
    ),
    NamedTensor(
        'excitation',
        np.array([.1, .2, .3, .4, .5])
    ),
    NamedTensor(
        'inhibition',
        -np.array([.1, .2, .3, .4, .5])
    )
)

neural_data = neural_data_1 + neural_data_2

In [22]:
neural_data

TensorGroup(potentials: ((4,)), plasticity: ((5,)), rates: ((4,)), spikes: ((4,)), excitation: ((5,)), inhibition: ((5,)))

### What if I still like dictionaries more?

In [23]:
n_neurons = 10
n_synapses = 1000
n_timepoints = 100

neural_data = TensorGroup(
    potentials=w1.copy(),
    plasticity=w2.copy(),
    rates=w3.copy()
)

# or
# neural_data = TensorGroup(
#     {
#         'potentials': np.random.rand(n_neurons, n_timepoints, n_synapses),
#         'plasticity': np.random.rand(n_synapses, n_timepoints),
#         'rate': np.random.rand(n_neurons, n_timepoints)
#     }
# )

In [24]:
neural_data['rates']

array([[0.52204761, 0.59265797, 0.25856925, 0.10785986, 0.81598852,
        0.93264882, 0.08565943, 0.41425655, 0.24621629, 0.42701444],
       [0.4468596 , 0.28251438, 0.32397303, 0.04865305, 0.56509122,
        0.11219784, 0.309262  , 0.25489199, 0.93840309, 0.79914837],
       [0.18119309, 0.22761645, 0.23941499, 0.29013364, 0.89963499,
        0.41632122, 0.78243297, 0.46283606, 0.44035838, 0.69753209],
       [0.63393529, 0.78405118, 0.3036635 , 0.08720888, 0.38903702,
        0.07006973, 0.55248663, 0.98170927, 0.22474091, 0.14495742],
       [0.03233896, 0.64247456, 0.17254489, 0.66644069, 0.04048339,
        0.65472692, 0.5432218 , 0.1863485 , 0.52492256, 0.06557487],
       [0.40485961, 0.15840864, 0.53858381, 0.32352748, 0.57657207,
        0.99257511, 0.11150721, 0.4729103 , 0.92390306, 0.98080936],
       [0.42862044, 0.05205699, 0.62063884, 0.88613878, 0.88430045,
        0.77347983, 0.25389497, 0.65390141, 0.94898988, 0.68696434],
       [0.1076473 , 0.03857778, 0.9932831

In [25]:
neural_data['plasticity'].min(), neural_data['plasticity'].max()

(0.00026848656952860317, 0.9999198841213022)

In [26]:
for key in neural_data.keys():
    neural_data[key] -= .5

In [27]:
neural_data['rates']

array([[ 0.02204761,  0.09265797, -0.24143075, -0.39214014,  0.31598852,
         0.43264882, -0.41434057, -0.08574345, -0.25378371, -0.07298556],
       [-0.0531404 , -0.21748562, -0.17602697, -0.45134695,  0.06509122,
        -0.38780216, -0.190738  , -0.24510801,  0.43840309,  0.29914837],
       [-0.31880691, -0.27238355, -0.26058501, -0.20986636,  0.39963499,
        -0.08367878,  0.28243297, -0.03716394, -0.05964162,  0.19753209],
       [ 0.13393529,  0.28405118, -0.1963365 , -0.41279112, -0.11096298,
        -0.42993027,  0.05248663,  0.48170927, -0.27525909, -0.35504258],
       [-0.46766104,  0.14247456, -0.32745511,  0.16644069, -0.45951661,
         0.15472692,  0.0432218 , -0.3136515 ,  0.02492256, -0.43442513],
       [-0.09514039, -0.34159136,  0.03858381, -0.17647252,  0.07657207,
         0.49257511, -0.38849279, -0.0270897 ,  0.42390306,  0.48080936],
       [-0.07137956, -0.44794301,  0.12063884,  0.38613878,  0.38430045,
         0.27347983, -0.24610503,  0.15390141

In [28]:
neural_data['plasticity'].min(), neural_data['plasticity'].max()

(-0.4997315134304714, 0.49991988412130217)

In [29]:
some_crazy_rule = np.exp(1 - (neural_data['potentials']@neural_data['plasticity']).mean(-1))
neural_data['rates'] /= some_crazy_rule

In [30]:
neural_data['rates']

array([[ 0.0106168 ,  0.06617958, -0.30390672, -0.09439851,  0.06118212,
         0.10759845, -0.09603363, -0.08278522, -0.02880955, -0.02006303],
       [-0.04493903, -0.35599249, -0.14194274, -0.37300998,  0.01459291,
        -0.1933345 , -0.06831331, -0.13034074,  0.08491789,  0.05999704],
       [-0.13612079, -0.20196336, -0.27277751, -0.0044045 ,  0.20522596,
        -0.03140591,  0.09037196, -0.02863803, -0.00353677,  0.04598782],
       [ 0.09168234,  0.12816669, -0.12401489, -0.07713693, -0.05962388,
        -0.29530078,  0.00716716,  0.43666583, -0.0791373 , -0.10352288],
       [-0.09247643,  0.06643601, -0.4399926 ,  0.09056814, -0.09070296,
         0.01837217,  0.09035721, -0.09630976,  0.00666881, -0.14431626],
       [-0.04127368, -0.28626816,  0.01733473, -0.04519581,  0.12363269,
         0.15254722, -0.22173933, -0.00572849,  0.19396416,  0.25268557],
       [-0.00825059, -1.01852414,  0.04832768,  0.09244156,  0.0649442 ,
         0.08902416, -1.29824564,  0.13521787

In [31]:
for key, value in neural_data.items():
    neural_data[key] = value * np.sin(value)

In [32]:
neural_data['rates']

array([[1.12714316e-04, 4.37654004e-03, 9.09441374e-02, 8.89784915e-03,
        3.74091723e-03, 1.15550994e-02, 9.20828945e-03, 6.84556781e-03,
        8.29875516e-04, 4.02498305e-04],
       [2.01883657e-03, 1.24070784e-01, 2.00801541e-02, 1.35932322e-01,
        2.12945551e-04, 3.71458097e-02, 4.66307956e-03, 1.69406462e-02,
        7.20238467e-03, 3.59748518e-03],
       [1.84717033e-02, 4.05124705e-02, 7.34882481e-02, 1.93995629e-05,
        4.18226685e-02, 9.86169315e-04, 8.15597871e-03, 8.20024780e-04,
        1.25087460e-05, 2.11413412e-03],
       [8.39388053e-03, 1.63817656e-02, 1.53403009e-02, 5.94420736e-03,
        3.55290110e-03, 8.59406859e-02, 5.13676971e-05, 1.84674931e-01,
        6.25617771e-03, 1.06978555e-02],
       [8.53970698e-03, 4.41049775e-03, 1.87407267e-01, 8.19137951e-03,
        8.21575014e-03, 3.37517629e-04, 8.15331976e-03, 9.26123806e-03,
        4.44727185e-05, 2.07549633e-02],
       [1.70303315e-03, 8.08347510e-02, 3.00477686e-04, 2.04196601e-03,
   

In [33]:
neural_data_1 = TensorGroup({
    'potentials': np.array([1, 1, 1, 1]),
    'plasticity': np.array([2, 2, 2, 2, 2]),
    'rates': np.array([1, 2, 3, 4])
})

neural_data_2 = TensorGroup({
    'potentials': np.array([.5, .5, .5, .5]),
    'plasticity': np.array([4, 4, 4, 4, 4]),
    'rates': np.array([4, 3, 2, 1])
})

neural_data = TensorGroup()
for key in neural_data_1.keys():
    neural_data[key] = neural_data_1[key] * neural_data_2[key]

In [34]:
neural_data['potentials']

array([0.5, 0.5, 0.5, 0.5])

In [35]:
neural_data['plasticity']

array([8, 8, 8, 8, 8])

In [36]:
neural_data['rates']

array([4, 6, 6, 4])

In [37]:
neural_data = TensorGroup()
for key in neural_data_1.keys():
    neural_data[key] = neural_data_1[key] * np.sin(neural_data_2[key])

In [38]:
neural_data['potentials']

array([0.47942554, 0.47942554, 0.47942554, 0.47942554])

In [39]:
neural_data['plasticity']

array([-1.51360499, -1.51360499, -1.51360499, -1.51360499, -1.51360499])

In [40]:
neural_data['rates']

array([-0.7568025 ,  0.28224002,  2.72789228,  3.36588394])

In [41]:
neural_data_1 = TensorGroup(
    {
        'potentials': np.array([1, 1, 1, 1]),
        'plasticity': np.array([2, 2, 2, 2, 2]),
        'rates': np.array([1, 2, 3, 4])
    }
)



neural_data = neural_data_1.copy()
neural_data.update(
    {
        'spikes': np.array([1, 0, 0, 1]),
        'excitation': np.array([.1, .2, .3, .4, .5]),
        'inhibition': -np.array([.1, .2, .3, .4, .5])
    }
)

In [42]:
neural_data

TensorGroup(potentials: ((4,)), plasticity: ((5,)), rates: ((4,)), spikes: ((4,)), excitation: ((5,)), inhibition: ((5,)))

### Everything works! Let's save that

In [43]:
neural_data.save('./neural_data.pkl')

### And read

In [44]:
loaded_neural_data = TensorGroup.load('./neural_data.pkl')

In [45]:
np.all(loaded_neural_data.rates == neural_data.rates)

True